[theme]
inherit = "basic"
stylesheets = [
    "css/custom.css",
]
pygments_style = { default = "default" }

[options]
collapse_navigation = "True"
sticky_navigation = "True"
navigation_depth = "4"
includehidden = "True"
display_version = "True"
prev_next_buttons_location = "bottom"
